intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

lib{iw4x-discord}: {hxx ixx txx cxx}{** -version} \
                   {hxx            }{    version} \
                   $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Discord SDK unpackaged dependency
#
discord_sdk_root = $src_root/../upstream/discord_social_sdk

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" \
                "-I$discord_sdk_root/include"

obja{*}: cxx.poptions += -DLIBIW4X_DISCORD_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBIW4X_DISCORD_SHARED_BUILD

if ($cxx.id == 'msvc')
{
  lib{iw4x}: cxx.loptions += "/LIBPATH:$discord_sdk_root/lib/release"

  lib{iw4x}: cxx.libs += discord_partner_sdk.lib
  lib{iw4x}: cxx.libs += wininet.lib

  lib{iw4x}: cxx.export.libs += discord_partner_sdk.lib
  lib{iw4x}: cxx.export.libs += wininet.lib
}

if ($cxx.class == 'gcc' && $cxx.target.system == 'mingw32')
{
  lib{iw4x}: cxx.loptions += "-L$discord_sdk_root/lib/release"

  lib{iw4x}: cxx.libs += -ldiscord_partner_sdk
  lib{iw4x}: cxx.libs += -lwininet

  lib{iw4x}: cxx.export.libs += -ldiscord_partner_sdk
  lib{iw4x}: cxx.export.libs += -lwininet
}

# Export options.
#
lib{iw4x-discord}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" \
                        "-I$discord_sdk_root/include"

  cxx.export.libs = $intf_libs
}

liba{iw4x-discord}: cxx.export.poptions += -DLIBIW4X_DISCORD_STATIC
libs{iw4x-discord}: cxx.export.poptions += -DLIBIW4X_DISCORD_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{iw4x-discord}: bin.lib.version = "-$version.project_id"
else
  lib{iw4x-discord}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libiw4x/discord/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libiw4x/discord/
  install.subdirs = true
}
