intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += xxhash%lib{xxhash}

lib{iw4x-utility}: {h   c  }{**         } \
                   {hxx cxx}{** -version} \
                   {hxx    }{    version} \
                   $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cc.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cc.poptions += -DLIBIW4X_UTILITY_STATIC_BUILD
objs{*}: cc.poptions += -DLIBIW4X_UTILITY_SHARED_BUILD

# Export options.
#
lib{iw4x-utility}:
{
  cc.export.poptions = "-I$out_root" "-I$src_root"
  cc.export.libs = $intf_libs
}

liba{iw4x-utility}: cc.export.poptions += -DLIBIW4X_UTILITY_STATIC
libs{iw4x-utility}: cc.export.poptions += -DLIBIW4X_UTILITY_SHARED

# Install into the libiw4x/utility/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{h hxx ixx txx}{*}:
{
  install         = include/libiw4x/utility/
  install.subdirs = true
}
