intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libiw4x-utility%lib{iw4x-utility}
import intf_libs += libboost-signals2%lib{boost_signals2}
import intf_libs += libimgui-render-dx9-docking%lib{imgui-render-dx9-docking}
import intf_libs += libimgui-platform-win32-docking%lib{imgui-platform-win32-docking}

lib{iw4x}: {hxx ixx txx cxx}{** -version} \
           {hxx            }{    version} \
           $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBIW4X_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBIW4X_SHARED_BUILD

# Export options.
#
lib{iw4x}: bin.lib.prefix = "lib"
lib{iw4x}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{iw4x}: cxx.export.poptions += -DLIBIW4X_STATIC
libs{iw4x}: cxx.export.poptions += -DLIBIW4X_SHARED

# Install into the libiw4x/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libiw4x/
  install.subdirs = true
}
