import! nasm = nasm%exe{nasm}

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libiw4x-utility%lib{iw4x-utility}

# Assembly stub for OOB packet interception
#
# There is no built-in rule to synthesize the lib{s,a} -> obj{s,a} -> asm{}
# dependencies so we have to do it manually.
#
libs{iw4x}: mod/objs{oob.asm.so.o}
liba{iw4x}: mod/obja{oob.asm.a.o}

# Dependencies of the object files on the .asm source file and recipe.
#
mod/objs{oob.asm.so.o}: mod/file{oob.asm} $nasm
{{
  diag nasm ($<[0])
  $nasm -f win64 -o $path($>) $path($<[0])
}}

mod/obja{oob.asm.a.o}: mod/file{oob.asm} $nasm
{{
  diag nasm ($<[0])
  $nasm -f win64 -o $path($>) $path($<[0])
}}

lib{iw4x}: {hxx ixx txx cxx}{**  -version} \
           {hxx            }{     version} \
           {def            }{**          } \
           $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBIW4X_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBIW4X_SHARED_BUILD

# Export options.
#
lib{iw4x}: bin.lib.prefix = "lib"
lib{iw4x}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{iw4x}: cxx.export.poptions += -DLIBIW4X_STATIC
libs{iw4x}: cxx.export.poptions += -DLIBIW4X_SHARED

# Install into the libiw4x/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libiw4x/
  install.subdirs = true
}
